const { Pool } = require('pg');
const { getDatabaseConfig } = require('./db-config');

const pool = new Pool(getDatabaseConfig());

const sampleEvents = [
  {
    name: 'Hội thảo Kết nối Doanh nghiệp 2024',
    code: 'SK-2024-001',
    event_date: '2026-05-30',
    start_time: '08:30',
    end_time: '11:30',
    location: 'Trung tâm Hội nghị Quốc gia, 57 Phạm Hùng, Hà Nội',
    expected_guests: 200,
    status: 'Sắp diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-1.jpg',
    event_type: 'Hội thảo / Seminar',
    event_format: 'Trực tiếp',
    short_description: 'Kết nối cộng đồng doanh nghiệp, chia sẻ kinh nghiệm và mở rộng cơ hội hợp tác phát triển.',
    detail_description: 'Hội thảo là nơi quy tụ các doanh nghiệp, chuyên gia và nhà quản lý cùng chia sẻ kinh nghiệm, giải pháp và xu hướng phát triển trong bối cảnh kinh tế mới. Đây là cơ hội tuyệt vời để mở rộng mạng lưới quan hệ và tìm kiếm cơ hội hợp tác.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 15600000,
  },
  {
    name: 'Workshop: Chuyển đổi số trong doanh nghiệp',
    code: 'SK-2024-002',
    event_date: '2026-06-05',
    start_time: '13:30',
    end_time: '16:30',
    location: 'TP. Hồ Chí Minh',
    expected_guests: 120,
    status: 'Đang mở đăng ký',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-2.jpg',
    event_type: 'Workshop / Đào tạo',
    event_format: 'Trực tiếp',
    short_description: 'Cập nhật xu hướng chuyển đổi số và ứng dụng công nghệ trong quản trị.',
    detail_description: 'Chương trình thực chiến hướng dẫn các bước chuyển đổi số cho doanh nghiệp vừa và nhỏ, tối ưu quy trình vận hành và ứng dụng AI tự động hóa.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 12000000,
  },
  {
    name: 'CEO Talk: Lãnh đạo trong thời đại mới',
    code: 'SK-2024-003',
    event_date: '2026-06-12',
    start_time: '09:00',
    end_time: '11:00',
    location: 'Đà Nẵng',
    expected_guests: 80,
    status: 'Sắp diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-3.jpg',
    event_type: 'Talkshow',
    event_format: 'Trực tiếp',
    short_description: 'Giao lưu cùng các CEO chia sẻ góc nhìn và chiến lược phát triển bền vững.',
    detail_description: 'Diễn đàn đối thoại trực tiếp cùng các nhà lãnh đạo hàng đầu về quản trị khủng hoảng, xây dựng văn hóa doanh nghiệp và phát triển bền vững.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 9500000,
  },
  {
    name: 'Hội nghị Thường niên WeLink 2024',
    code: 'SK-2024-004',
    event_date: '2026-04-20',
    start_time: '08:00',
    end_time: '17:00',
    location: 'Hà Nội',
    expected_guests: 350,
    status: 'Đã diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-4.jpg',
    event_type: 'Đại hội / Hội nghị',
    event_format: 'Trực tiếp',
    short_description: 'Tổng kết hoạt động, định hướng chiến lược phát triển năm mới.',
    detail_description: 'Sự kiện lớn nhất năm quy tụ toàn thể các thành viên, đối tác chiến lược và ban lãnh đạo Nghiêng Complex & WeLink.',
    mc_fee: 500000,
    speaker_fee: 500000,
    support_fee: 300000,
    closer_fee: 300000,
    tea_break_fee: 2500000,
    fee: 28000000,
  },
  {
    name: 'Đào tạo Kỹ năng mềm cho nhân sự',
    code: 'SK-2024-005',
    event_date: '2026-06-25',
    start_time: '08:30',
    end_time: '11:30',
    location: 'Hà Nội',
    expected_guests: 60,
    status: 'Sắp diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-5.jpg',
    event_type: 'Đào tạo nội bộ',
    event_format: 'Trực tiếp',
    short_description: 'Nâng cao kỹ năng giao tiếp, làm việc nhóm và quản lý thời gian hiệu quả.',
    detail_description: 'Khóa huấn luyện chuyên sâu dành cho đội ngũ nhân sự nâng cao năng lực làm việc, giao tiếp hiệu quả và tạo sự gắn kết trong tổ chức.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1000000,
    fee: 8000000,
  },
  {
    name: 'Hội thảo Ứng dụng AI trong kinh doanh',
    code: 'SK-2024-006',
    event_date: '2026-06-28',
    start_time: '13:30',
    end_time: '16:30',
    location: 'Hà Nội',
    expected_guests: 180,
    status: 'Đang mở đăng ký',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-6.jpg',
    event_type: 'Hội thảo công nghệ',
    event_format: 'Trực tiếp',
    short_description: 'Khám phá công nghệ AI và cách ứng dụng vào thực tế kinh doanh.',
    detail_description: 'Giới thiệu các công cụ trí tuệ nhân tạo đột phá trong bán hàng, marketing, chăm sóc khách hàng và quản lý tài chính doanh nghiệp.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1500000,
    fee: 14000000,
  },
  {
    name: 'Teambuilding – Gắn kết đội ngũ',
    code: 'SK-2024-007',
    event_date: '2026-07-02',
    start_time: '08:00',
    end_time: '17:00',
    location: 'Đà Lạt',
    expected_guests: 90,
    status: 'Sắp diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-7.jpg',
    event_type: 'Teambuilding',
    event_format: 'Trực tiếp',
    short_description: 'Tăng cường tinh thần đồng đội và xây dựng văn hóa WeLink.',
    detail_description: 'Chuỗi hoạt động thể chất và trò chơi trí tuệ giúp các thành viên thấu hiểu, gắn kết và cùng nhau vượt qua thử thách.',
    mc_fee: 300000,
    speaker_fee: 200000,
    support_fee: 300000,
    closer_fee: 200000,
    tea_break_fee: 2000000,
    fee: 22000000,
  },
  {
    name: 'Lễ ra mắt sản phẩm mới',
    code: 'SK-2024-008',
    event_date: '2026-07-15',
    start_time: '09:00',
    end_time: '11:30',
    location: 'TP. Hồ Chí Minh',
    expected_guests: 250,
    status: 'Đã diễn ra',
    approval_status: 'Đã duyệt',
    image_url: '/events/event-8.jpg',
    event_type: 'Ra mắt sản phẩm',
    event_format: 'Trực tiếp',
    short_description: 'Giới thiệu sản phẩm chiến lược và cơ hội hợp tác kinh doanh.',
    detail_description: 'Lễ công bố dòng sản phẩm đột phá mới của Nghiêng Complex và chính sách phân phối hấp dẫn cho các đối tác toàn quốc.',
    mc_fee: 400000,
    speaker_fee: 500000,
    support_fee: 300000,
    closer_fee: 300000,
    tea_break_fee: 2000000,
    fee: 18500000,
  },
];

async function run() {
  try {
    const userRes = await pool.query("SELECT id FROM users WHERE role = 'Admin' LIMIT 1");
    const adminId = userRes.rows.length > 0 ? userRes.rows[0].id : null;

    for (let i = 0; i < sampleEvents.length; i++) {
      const e = sampleEvents[i];
      const id = i + 1;

      // Upsert event by id
      const check = await pool.query('SELECT id FROM events WHERE id = $1', [id]);
      if (check.rows.length > 0) {
        await pool.query(
          `UPDATE events SET
            name = $1,
            code = $2,
            event_date = $3,
            start_time = $4,
            end_time = $5,
            location = $6,
            expected_guests = $7,
            status = $8,
            approval_status = $9,
            image_url = $10,
            event_type = $11,
            event_format = $12,
            short_description = $13,
            detail_description = $14,
            mc_fee = $15,
            speaker_fee = $16,
            support_fee = $17,
            closer_fee = $18,
            tea_break_fee = $19,
            fee = $20,
            manager_id = COALESCE(manager_id, $21),
            creator_id = COALESCE(creator_id, $21)
          WHERE id = $22`,
          [
            e.name,
            e.code,
            e.event_date,
            e.start_time,
            e.end_time,
            e.location,
            e.expected_guests,
            e.status,
            e.approval_status,
            e.image_url,
            e.event_type,
            e.event_format,
            e.short_description,
            e.detail_description,
            e.mc_fee,
            e.speaker_fee,
            e.support_fee,
            e.closer_fee,
            e.tea_break_fee,
            e.fee,
            adminId,
            id,
          ]
        );
      } else {
        await pool.query(
          `INSERT INTO events (
            id, name, code, event_date, start_time, end_time, location, expected_guests,
            status, approval_status, image_url, event_type, event_format,
            short_description, detail_description, mc_fee, speaker_fee, support_fee,
            closer_fee, tea_break_fee, fee, manager_id, creator_id
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)`,
          [
            id,
            e.name,
            e.code,
            e.event_date,
            e.start_time,
            e.end_time,
            e.location,
            e.expected_guests,
            e.status,
            e.approval_status,
            e.image_url,
            e.event_type,
            e.event_format,
            e.short_description,
            e.detail_description,
            e.mc_fee,
            e.speaker_fee,
            e.support_fee,
            e.closer_fee,
            e.tea_break_fee,
            e.fee,
            adminId,
            adminId,
          ]
        );
      }
    }

    // Reset sequence if needed
    await pool.query(`SELECT setval('events_id_seq', (SELECT MAX(id) FROM events))`);

    console.log('Successfully seeded 8 rich events matching Image 3/5/6!');
  } catch (err) {
    console.error('Error seeding events:', err);
  } finally {
    pool.end();
  }
}

run();
