const { Pool } = require('pg');
const pool = new Pool({
  user: 'postgres',
  password: '1111222267',
  host: 'localhost',
  port: 5433,
  database: 'postgismap',
});

async function seedFullMembers() {
  console.log('Seeding rich member data...');

  const membersData = [
    {
      full_name: 'Nhung Nguyễn',
      phone: '0000000001',
      email: 'nhungnguyen1722@gmail.com',
      role: 'Admin',
      classification: 'Nhân sự',
      title: 'Giám đốc',
      referral_group: 'Thành viên hệ thống',
      ref_code: 'REF001',
      source: 'Nội bộ',
      join_date: '2025-01-01',
      status: 'Đang hoạt động',
      guest_count: 12,
      bank_account: 'MB Bank - 0900000001',
      identity_card: '001200000001',
      is_team_leader_eligible: true,
      notes: 'Quản trị viên tối cao hệ thống WeLink'
    },
    {
      full_name: 'Nguyễn Tuấn',
      phone: '0000000002',
      email: 'tuan161022@gmail.com',
      role: 'Nhân viên',
      classification: 'Nhân sự',
      title: 'Trưởng phòng',
      referral_group: 'Thành viên hệ thống',
      ref_code: 'REF002',
      source: 'Nội bộ',
      join_date: '2025-02-15',
      status: 'Đang hoạt động',
      guest_count: 8,
      bank_account: 'Techcombank - 1903000002',
      identity_card: '001200000002',
      is_team_leader_eligible: true,
      notes: 'Quản lý sự kiện và đối tác'
    },
    {
      full_name: 'Nguyễn Văn An',
      phone: '0901234567',
      email: 'an.nguyen@welink.vn',
      role: 'MC',
      classification: 'Nhân sự',
      title: 'Thành viên',
      referral_group: 'Khách vãng lai',
      ref_code: 'REF_AN01',
      source: 'Facebook',
      join_date: '2025-03-10',
      status: 'Đang hoạt động',
      guest_count: 5,
      bank_account: 'Vietcombank - 0011001234567',
      identity_card: '001200000003',
      is_team_leader_eligible: false,
      notes: 'MC chuyên nghiệp sự kiện lớn'
    },
    {
      full_name: 'Trần Thị Bình',
      phone: '0902345678',
      email: 'binh.tran@welink.vn',
      role: 'Thuyết trình',
      classification: 'Nhân sự',
      title: 'Trưởng phòng',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_BINH02',
      referrer_id: 1,
      source: 'Bạn bè giới thiệu',
      join_date: '2025-03-15',
      status: 'Đang hoạt động',
      guest_count: 7,
      bank_account: 'BIDV - 12010002345678',
      identity_card: '001200000004',
      is_team_leader_eligible: true,
      notes: 'Diễn giả chính chuyên đề Marketing'
    },
    {
      full_name: 'Lê Hoàng Cường',
      phone: '0903456789',
      email: 'cuong.le@welink.vn',
      role: 'Chốt sự kiện',
      classification: 'Pro Sale',
      title: 'Phó Giám đốc',
      referral_group: 'Mã mời từ thành viên (Referral Code)',
      ref_code: 'REF_CUONG03',
      referrer_id: 1,
      source: 'Hội thảo',
      join_date: '2025-04-01',
      status: 'Đang hoạt động',
      guest_count: 15,
      bank_account: 'VPBank - 903456789',
      identity_card: '001200000005',
      is_team_leader_eligible: true,
      notes: 'Chốt hợp đồng xuất sắc quý 1'
    },
    {
      full_name: 'Phạm Thị Dung',
      phone: '0904567890',
      email: 'dung.pham@welink.vn',
      role: 'Phụng sự',
      classification: 'Nhân sự',
      title: 'Thành viên',
      referral_group: 'Khách vãng lai',
      ref_code: 'REF_DUNG04',
      source: 'Zalo',
      join_date: '2025-04-10',
      status: 'Đang hoạt động',
      guest_count: 3,
      bank_account: 'ACB - 200456789',
      identity_card: '001200000006',
      is_team_leader_eligible: false,
      notes: 'Hậu cần & điều phối bàn tiệc trà'
    },
    {
      full_name: 'Hoàng Văn Em',
      phone: '0905678901',
      email: 'em.hoang@welink.vn',
      role: 'Kinh doanh',
      classification: 'Sale',
      title: 'Thành viên',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_EM05',
      referrer_id: 5,
      source: 'Tik Tok',
      join_date: '2025-05-01',
      status: 'Đang hoạt động',
      guest_count: 9,
      bank_account: 'TPBank - 0905678901',
      identity_card: '001200000007',
      is_team_leader_eligible: false,
      notes: 'Đạt chỉ tiêu doanh số tháng 5'
    },
    {
      full_name: 'Đỗ Thị Phương',
      phone: '0906789012',
      email: 'phuong.do@welink.vn',
      role: 'Team Leader',
      classification: 'Pro Sale',
      title: 'Trưởng phòng',
      referral_group: 'Mã mời từ thành viên (Referral Code)',
      ref_code: 'REF_PHUONG06',
      referrer_id: 1,
      source: 'Sự kiện networking',
      join_date: '2025-05-15',
      status: 'Đang hoạt động',
      guest_count: 20,
      bank_account: 'MB Bank - 0906789012',
      identity_card: '001200000008',
      is_team_leader_eligible: true,
      notes: 'Leader Team Hà Đông'
    },
    {
      full_name: 'Vũ Kế Toán',
      phone: '0907890123',
      email: 'ketoan.vu@welink.vn',
      role: 'Kế toán',
      classification: 'Nhân sự',
      title: 'Trưởng phòng',
      referral_group: 'Thành viên hệ thống',
      ref_code: 'REF_KETOAN07',
      source: 'Nội bộ',
      join_date: '2025-06-01',
      status: 'Hoạt động',
      guest_count: 2,
      bank_account: 'VietinBank - 101890789012',
      identity_card: '001200000009',
      is_team_leader_eligible: false,
      notes: 'Kiểm soát thu chi sự kiện'
    },
    {
      full_name: 'Bùi Công Nghệ',
      phone: '0908901234',
      email: 'congnghe.bui@welink.vn',
      role: 'Công nghệ',
      classification: 'Nhân sự',
      title: 'Trưởng phòng',
      referral_group: 'Thành viên hệ thống',
      ref_code: 'REF_TECH08',
      source: 'Nội bộ',
      join_date: '2025-06-05',
      status: 'Hoạt động',
      guest_count: 1,
      bank_account: 'Techcombank - 1908901234',
      identity_card: '001200000010',
      is_team_leader_eligible: false,
      notes: 'Quản trị nền tảng và kỹ thuật check-in'
    },
    {
      full_name: 'Ngô Quốc Bảo',
      phone: '0911223344',
      email: 'bao.ngo@welink.vn',
      role: 'Kinh doanh',
      classification: 'Sale',
      title: 'Thành viên',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_BAO09',
      referrer_id: 8,
      source: 'Facebook Ads',
      join_date: '2025-06-12',
      status: 'Hoạt động',
      guest_count: 4,
      bank_account: 'VPBank - 0911223344',
      identity_card: '001200000011',
      is_team_leader_eligible: false,
      notes: 'Thành viên team Hà Đông'
    },
    {
      full_name: 'Trịnh Thị Hà',
      phone: '0912334455',
      email: 'ha.trinh@welink.vn',
      role: 'Lễ tân',
      classification: 'Nhân sự',
      title: 'Thành viên',
      referral_group: 'Khách vãng lai',
      ref_code: 'REF_HA10',
      source: 'Tuyển dụng',
      join_date: '2025-06-20',
      status: 'Hoạt động',
      guest_count: 6,
      bank_account: 'ACB - 0912334455',
      identity_card: '001200000012',
      is_team_leader_eligible: false,
      notes: 'Lễ tân đón tiếp khách và in thẻ check-in'
    },
    {
      full_name: 'Đặng Minh Khang',
      phone: '0913445566',
      email: 'khang.dang@welink.vn',
      role: 'Kinh doanh',
      classification: 'Pro Sale',
      title: 'Phó Giám đốc',
      referral_group: 'Mã mời từ thành viên (Referral Code)',
      ref_code: 'REF_KHANG11',
      referrer_id: 5,
      source: 'Hội nghị BNI',
      join_date: '2025-07-01',
      status: 'Hoạt động',
      guest_count: 18,
      bank_account: 'Vietcombank - 0021009134455',
      identity_card: '001200000013',
      is_team_leader_eligible: true,
      notes: 'Chuyên gia đào tạo bán hàng'
    },
    {
      full_name: 'Vũ Thị Cúc',
      phone: '0914556677',
      email: 'cuc.vu@welink.vn',
      role: 'Admin',
      classification: 'Nhân sự',
      title: 'Chủ tịch',
      referral_group: 'Thành viên hệ thống',
      ref_code: 'REF_CUC12',
      source: 'Sáng lập viên',
      join_date: '2024-12-01',
      status: 'Hoạt động',
      guest_count: 30,
      bank_account: 'MB Bank - 0914556677',
      identity_card: '001200000014',
      is_team_leader_eligible: true,
      notes: 'Người duyệt điều kiện Team Leader & duyệt chi phí sự kiện'
    },
    {
      full_name: 'Lý Quốc Trí',
      phone: '0915667788',
      email: 'tri.ly@gmail.com',
      role: 'Khác',
      classification: 'Khách mời',
      title: 'Thành viên',
      referral_group: 'Khách vãng lai',
      ref_code: 'REF_TRI13',
      source: 'Website',
      join_date: '2025-07-15',
      status: 'Hoạt động',
      guest_count: 1,
      bank_account: 'Techcombank - 0915667788',
      identity_card: '001200000015',
      is_team_leader_eligible: false,
      notes: 'Đối tác tiềm năng mảng F&B'
    },
    {
      full_name: 'Phan Mỹ Linh',
      phone: '0916778899',
      email: 'linh.phan@welink.vn',
      role: 'Thuyết trình',
      classification: 'CTV',
      title: 'Thành viên',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_LINH14',
      referrer_id: 4,
      source: 'Bạn bè',
      join_date: '2025-07-20',
      status: 'Hoạt động',
      guest_count: 3,
      bank_account: 'VPBank - 0916778899',
      identity_card: '001200000016',
      is_team_leader_eligible: false,
      notes: 'Cộng tác viên mảng truyền thông số'
    },
    {
      full_name: 'Dương Văn Kiên',
      phone: '0917889900',
      email: 'kien.duong@welink.vn',
      role: 'Chốt sự kiện',
      classification: 'Pro Sale',
      title: 'Trưởng phòng',
      referral_group: 'Mã mời từ thành viên (Referral Code)',
      ref_code: 'REF_KIEN15',
      referrer_id: 13,
      source: 'Hội doanh nghiệp trẻ',
      join_date: '2025-08-01',
      status: 'Hoạt động',
      guest_count: 11,
      bank_account: 'BIDV - 0917889900',
      identity_card: '001200000017',
      is_team_leader_eligible: true,
      notes: 'Team Leader Vĩnh Phúc'
    },
    {
      full_name: 'Mai Thanh Tâm',
      phone: '0918990011',
      email: 'tam.mai@welink.vn',
      role: 'Phụng sự',
      classification: 'Nhân sự',
      title: 'Thành viên',
      referral_group: 'Khách vãng lai',
      ref_code: 'REF_TAM16',
      source: 'Zalo Group',
      join_date: '2025-08-10',
      status: 'Hoạt động',
      guest_count: 4,
      bank_account: 'ACB - 0918990011',
      identity_card: '001200000018',
      is_team_leader_eligible: false,
      notes: 'Phụ trách âm thanh ánh sáng'
    },
    {
      full_name: 'Tạ Minh Nhật',
      phone: '0919001122',
      email: 'nhat.ta@welink.vn',
      role: 'Kinh doanh',
      classification: 'Sale',
      title: 'Thành viên',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_NHAT17',
      referrer_id: 17,
      source: 'Facebook',
      join_date: '2025-08-15',
      status: 'Không hoạt động',
      guest_count: 0,
      bank_account: 'Vietcombank - 0919001122',
      identity_card: '001200000019',
      is_team_leader_eligible: false,
      notes: 'Tạm nghỉ phép cá nhân'
    },
    {
      full_name: 'Cao Hoàng Yến',
      phone: '0920112233',
      email: 'yen.cao@welink.vn',
      role: 'MC',
      classification: 'CTV',
      title: 'Thành viên',
      referral_group: 'Chọn người mời trong hệ thống',
      ref_code: 'REF_YEN18',
      referrer_id: 3,
      source: 'CLB MC Hà Nội',
      join_date: '2025-08-25',
      status: 'Hoạt động',
      guest_count: 2,
      bank_account: 'MB Bank - 0920112233',
      identity_card: '001200000020',
      is_team_leader_eligible: false,
      notes: 'MC dự bị các sự kiện song ngữ'
    }
  ];

  for (const m of membersData) {
    const existing = await pool.query('SELECT id FROM users WHERE phone = $1', [m.phone]);
    if (existing.rows.length === 0) {
      await pool.query(
        `INSERT INTO users (
          full_name, phone, email, role, classification, title,
          referral_group, ref_code, referrer_id, source, join_date,
          status, guest_count, bank_account, identity_card,
          is_team_leader_eligible, notes
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)`,
        [
          m.full_name, m.phone, m.email, m.role, m.classification, m.title,
          m.referral_group, m.ref_code, m.referrer_id || null, m.source, m.join_date,
          m.status, m.guest_count, m.bank_account, m.identity_card,
          m.is_team_leader_eligible, m.notes
        ]
      );
    } else {
      await pool.query(
        `UPDATE users SET
          full_name = $1, email = $2, role = $3, classification = $4, title = $5,
          referral_group = $6, ref_code = $7, referrer_id = $8, source = $9, join_date = $10,
          status = $11, guest_count = $12, bank_account = $13, identity_card = $14,
          is_team_leader_eligible = $15, notes = $16
        WHERE phone = $17`,
        [
          m.full_name, m.email, m.role, m.classification, m.title,
          m.referral_group, m.ref_code, m.referrer_id || null, m.source, m.join_date,
          m.status, m.guest_count, m.bank_account, m.identity_card,
          m.is_team_leader_eligible, m.notes, m.phone
        ]
      );
    }
  }

  const all = await pool.query('SELECT id, full_name, phone, role, classification, title, guest_count, referral_group, status FROM users ORDER BY id ASC');
  console.log(`Successfully seeded ${all.rows.length} members.`);
  console.table(all.rows);

  await pool.end();
}

seedFullMembers().catch((err) => {
  console.error(err);
  process.exit(1);
});
