const { Pool } = require('pg');
const { getDatabaseConfig } = require('./db-config');

const pool = new Pool(getDatabaseConfig());

const sampleEvents = [
  {
    name: 'Há»™i tháº£o Káº¿t ná»‘i Doanh nghiá»‡p 2024',
    code: 'SK-2024-001',
    event_date: '2026-05-30',
    start_time: '08:30',
    end_time: '11:30',
    location: 'Trung tÃ¢m Há»™i nghá»‹ Quá»‘c gia, 57 Pháº¡m HÃ¹ng, HÃ  Ná»™i',
    expected_guests: 200,
    status: 'Sáº¯p diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-1.jpg',
    event_type: 'Há»™i tháº£o / Seminar',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'Káº¿t ná»‘i cá»™ng Ä‘á»“ng doanh nghiá»‡p, chia sáº» kinh nghiá»‡m vÃ  má»Ÿ rá»™ng cÆ¡ há»™i há»£p tÃ¡c phÃ¡t triá»ƒn.',
    detail_description: 'Há»™i tháº£o lÃ  nÆ¡i quy tá»¥ cÃ¡c doanh nghiá»‡p, chuyÃªn gia vÃ  nhÃ  quáº£n lÃ½ cÃ¹ng chia sáº» kinh nghiá»‡m, giáº£i phÃ¡p vÃ  xu hÆ°á»›ng phÃ¡t triá»ƒn trong bá»‘i cáº£nh kinh táº¿ má»›i. ÄÃ¢y lÃ  cÆ¡ há»™i tuyá»‡t vá»i Ä‘á»ƒ má»Ÿ rá»™ng máº¡ng lÆ°á»›i quan há»‡ vÃ  tÃ¬m kiáº¿m cÆ¡ há»™i há»£p tÃ¡c.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 15600000,
  },
  {
    name: 'Workshop: Chuyá»ƒn Ä‘á»•i sá»‘ trong doanh nghiá»‡p',
    code: 'SK-2024-002',
    event_date: '2026-06-05',
    start_time: '13:30',
    end_time: '16:30',
    location: 'TP. Há»“ ChÃ­ Minh',
    expected_guests: 120,
    status: 'Äang má»Ÿ Ä‘Äƒng kÃ½',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-2.jpg',
    event_type: 'Workshop / ÄÃ o táº¡o',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'Cáº­p nháº­t xu hÆ°á»›ng chuyá»ƒn Ä‘á»•i sá»‘ vÃ  á»©ng dá»¥ng cÃ´ng nghá»‡ trong quáº£n trá»‹.',
    detail_description: 'ChÆ°Æ¡ng trÃ¬nh thá»±c chiáº¿n hÆ°á»›ng dáº«n cÃ¡c bÆ°á»›c chuyá»ƒn Ä‘á»•i sá»‘ cho doanh nghiá»‡p vá»«a vÃ  nhá», tá»‘i Æ°u quy trÃ¬nh váº­n hÃ nh vÃ  á»©ng dá»¥ng AI tá»± Ä‘á»™ng hÃ³a.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 12000000,
  },
  {
    name: 'CEO Talk: LÃ£nh Ä‘áº¡o trong thá»i Ä‘áº¡i má»›i',
    code: 'SK-2024-003',
    event_date: '2026-06-12',
    start_time: '09:00',
    end_time: '11:00',
    location: 'ÄÃ  Náºµng',
    expected_guests: 80,
    status: 'Sáº¯p diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-3.jpg',
    event_type: 'Talkshow',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'Giao lÆ°u cÃ¹ng cÃ¡c CEO chia sáº» gÃ³c nhÃ¬n vÃ  chiáº¿n lÆ°á»£c phÃ¡t triá»ƒn bá»n vá»¯ng.',
    detail_description: 'Diá»…n Ä‘Ã n Ä‘á»‘i thoáº¡i trá»±c tiáº¿p cÃ¹ng cÃ¡c nhÃ  lÃ£nh Ä‘áº¡o hÃ ng Ä‘áº§u vá» quáº£n trá»‹ khá»§ng hoáº£ng, xÃ¢y dá»±ng vÄƒn hÃ³a doanh nghiá»‡p vÃ  phÃ¡t triá»ƒn bá»n vá»¯ng.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1250000,
    fee: 9500000,
  },
  {
    name: 'Há»™i nghá»‹ ThÆ°á»ng niÃªn Nghiêng Complex 2024',
    code: 'SK-2024-004',
    event_date: '2026-04-20',
    start_time: '08:00',
    end_time: '17:00',
    location: 'HÃ  Ná»™i',
    expected_guests: 350,
    status: 'ÄÃ£ diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-4.jpg',
    event_type: 'Äáº¡i há»™i / Há»™i nghá»‹',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'Tá»•ng káº¿t hoáº¡t Ä‘á»™ng, Ä‘á»‹nh hÆ°á»›ng chiáº¿n lÆ°á»£c phÃ¡t triá»ƒn nÄƒm má»›i.',
    detail_description: 'Sá»± kiá»‡n lá»›n nháº¥t nÄƒm quy tá»¥ toÃ n thá»ƒ cÃ¡c thÃ nh viÃªn, Ä‘á»‘i tÃ¡c chiáº¿n lÆ°á»£c vÃ  ban lÃ£nh Ä‘áº¡o NghiÃªng Complex & Nghiêng Complex.',
    mc_fee: 500000,
    speaker_fee: 500000,
    support_fee: 300000,
    closer_fee: 300000,
    tea_break_fee: 2500000,
    fee: 28000000,
  },
  {
    name: 'ÄÃ o táº¡o Ká»¹ nÄƒng má»m cho nhÃ¢n sá»±',
    code: 'SK-2024-005',
    event_date: '2026-06-25',
    start_time: '08:30',
    end_time: '11:30',
    location: 'HÃ  Ná»™i',
    expected_guests: 60,
    status: 'Sáº¯p diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-5.jpg',
    event_type: 'ÄÃ o táº¡o ná»™i bá»™',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'NÃ¢ng cao ká»¹ nÄƒng giao tiáº¿p, lÃ m viá»‡c nhÃ³m vÃ  quáº£n lÃ½ thá»i gian hiá»‡u quáº£.',
    detail_description: 'KhÃ³a huáº¥n luyá»‡n chuyÃªn sÃ¢u dÃ nh cho Ä‘á»™i ngÅ© nhÃ¢n sá»± nÃ¢ng cao nÄƒng lá»±c lÃ m viá»‡c, giao tiáº¿p hiá»‡u quáº£ vÃ  táº¡o sá»± gáº¯n káº¿t trong tá»• chá»©c.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1000000,
    fee: 8000000,
  },
  {
    name: 'Há»™i tháº£o á»¨ng dá»¥ng AI trong kinh doanh',
    code: 'SK-2024-006',
    event_date: '2026-06-28',
    start_time: '13:30',
    end_time: '16:30',
    location: 'HÃ  Ná»™i',
    expected_guests: 180,
    status: 'Äang má»Ÿ Ä‘Äƒng kÃ½',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-6.jpg',
    event_type: 'Há»™i tháº£o cÃ´ng nghá»‡',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'KhÃ¡m phÃ¡ cÃ´ng nghá»‡ AI vÃ  cÃ¡ch á»©ng dá»¥ng vÃ o thá»±c táº¿ kinh doanh.',
    detail_description: 'Giá»›i thiá»‡u cÃ¡c cÃ´ng cá»¥ trÃ­ tuá»‡ nhÃ¢n táº¡o Ä‘á»™t phÃ¡ trong bÃ¡n hÃ ng, marketing, chÄƒm sÃ³c khÃ¡ch hÃ ng vÃ  quáº£n lÃ½ tÃ i chÃ­nh doanh nghiá»‡p.',
    mc_fee: 200000,
    speaker_fee: 300000,
    support_fee: 200000,
    closer_fee: 200000,
    tea_break_fee: 1500000,
    fee: 14000000,
  },
  {
    name: 'Teambuilding â€“ Gáº¯n káº¿t Ä‘á»™i ngÅ©',
    code: 'SK-2024-007',
    event_date: '2026-07-02',
    start_time: '08:00',
    end_time: '17:00',
    location: 'ÄÃ  Láº¡t',
    expected_guests: 90,
    status: 'Sáº¯p diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-7.jpg',
    event_type: 'Teambuilding',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'TÄƒng cÆ°á»ng tinh tháº§n Ä‘á»“ng Ä‘á»™i vÃ  xÃ¢y dá»±ng vÄƒn hÃ³a Nghiêng Complex.',
    detail_description: 'Chuá»—i hoáº¡t Ä‘á»™ng thá»ƒ cháº¥t vÃ  trÃ² chÆ¡i trÃ­ tuá»‡ giÃºp cÃ¡c thÃ nh viÃªn tháº¥u hiá»ƒu, gáº¯n káº¿t vÃ  cÃ¹ng nhau vÆ°á»£t qua thá»­ thÃ¡ch.',
    mc_fee: 300000,
    speaker_fee: 200000,
    support_fee: 300000,
    closer_fee: 200000,
    tea_break_fee: 2000000,
    fee: 22000000,
  },
  {
    name: 'Lá»… ra máº¯t sáº£n pháº©m má»›i',
    code: 'SK-2024-008',
    event_date: '2026-07-15',
    start_time: '09:00',
    end_time: '11:30',
    location: 'TP. Há»“ ChÃ­ Minh',
    expected_guests: 250,
    status: 'ÄÃ£ diá»…n ra',
    approval_status: 'ÄÃ£ duyá»‡t',
    image_url: '/events/event-8.jpg',
    event_type: 'Ra máº¯t sáº£n pháº©m',
    event_format: 'Trá»±c tiáº¿p',
    short_description: 'Giá»›i thiá»‡u sáº£n pháº©m chiáº¿n lÆ°á»£c vÃ  cÆ¡ há»™i há»£p tÃ¡c kinh doanh.',
    detail_description: 'Lá»… cÃ´ng bá»‘ dÃ²ng sáº£n pháº©m Ä‘á»™t phÃ¡ má»›i cá»§a NghiÃªng Complex vÃ  chÃ­nh sÃ¡ch phÃ¢n phá»‘i háº¥p dáº«n cho cÃ¡c Ä‘á»‘i tÃ¡c toÃ n quá»‘c.',
    mc_fee: 400000,
    speaker_fee: 500000,
    support_fee: 300000,
    closer_fee: 300000,
    tea_break_fee: 2000000,
    fee: 18500000,
  },
];

async function run() {
  try {
    const userRes = await pool.query("SELECT id FROM users WHERE role = 'Admin' LIMIT 1");
    const adminId = userRes.rows.length > 0 ? userRes.rows[0].id : null;

    for (let i = 0; i < sampleEvents.length; i++) {
      const e = sampleEvents[i];
      const id = i + 1;

      // Upsert event by id
      const check = await pool.query('SELECT id FROM events WHERE id = $1', [id]);
      if (check.rows.length > 0) {
        await pool.query(
          `UPDATE events SET
            name = $1,
            code = $2,
            event_date = $3,
            start_time = $4,
            end_time = $5,
            location = $6,
            expected_guests = $7,
            status = $8,
            approval_status = $9,
            image_url = $10,
            event_type = $11,
            event_format = $12,
            short_description = $13,
            detail_description = $14,
            mc_fee = $15,
            speaker_fee = $16,
            support_fee = $17,
            closer_fee = $18,
            tea_break_fee = $19,
            fee = $20,
            manager_id = COALESCE(manager_id, $21),
            creator_id = COALESCE(creator_id, $21)
          WHERE id = $22`,
          [
            e.name,
            e.code,
            e.event_date,
            e.start_time,
            e.end_time,
            e.location,
            e.expected_guests,
            e.status,
            e.approval_status,
            e.image_url,
            e.event_type,
            e.event_format,
            e.short_description,
            e.detail_description,
            e.mc_fee,
            e.speaker_fee,
            e.support_fee,
            e.closer_fee,
            e.tea_break_fee,
            e.fee,
            adminId,
            id,
          ]
        );
      } else {
        await pool.query(
          `INSERT INTO events (
            id, name, code, event_date, start_time, end_time, location, expected_guests,
            status, approval_status, image_url, event_type, event_format,
            short_description, detail_description, mc_fee, speaker_fee, support_fee,
            closer_fee, tea_break_fee, fee, manager_id, creator_id
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)`,
          [
            id,
            e.name,
            e.code,
            e.event_date,
            e.start_time,
            e.end_time,
            e.location,
            e.expected_guests,
            e.status,
            e.approval_status,
            e.image_url,
            e.event_type,
            e.event_format,
            e.short_description,
            e.detail_description,
            e.mc_fee,
            e.speaker_fee,
            e.support_fee,
            e.closer_fee,
            e.tea_break_fee,
            e.fee,
            adminId,
            adminId,
          ]
        );
      }
    }

    // Reset sequence if needed
    await pool.query(`SELECT setval('events_id_seq', (SELECT MAX(id) FROM events))`);

    console.log('Successfully seeded 8 rich events matching Image 3/5/6!');
  } catch (err) {
    console.error('Error seeding events:', err);
  } finally {
    pool.end();
  }
}

run();

